---
name: Deploy AWS CDK

"on":
  workflow_call:
    secrets:
      AWS_ROLE_ARN:
        required: true
      CERTIFICATE_ARN:
        required: true
      HOSTED_ZONE_ID:
        required: true
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: cdk-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    permissions:
      contents: read
      id-token: write
    env:
      AWS_REGION: ap-northeast-1
      HOSTED_ZONE_DOMAIN_NAME: c4se.jp
      SITE_DOMAIN_NAME: martian-imperial-year-table.c4se.jp
    steps:
      - name: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Node.jsを使ふ
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          cache: npm
          node-version: 24

      - name: 依存するlibraryを入れる
        run: npm ci

      - name: Web siteをbuildする
        run: npm run -w martian_ui build

      - name: AWSに認可をとる
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: CDKの依存するlibraryを入れる
        run: npm install --prefix cdk

      - name: CDK deploy
        env:
          CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
        run: |
          npx cdk deploy --require-approval never \
            -c certificateArn="${CERTIFICATE_ARN}" \
            -c hostedZoneDomainName="${HOSTED_ZONE_DOMAIN_NAME}" \
            -c hostedZoneId="${HOSTED_ZONE_ID}" \
            -c siteDomainName="${SITE_DOMAIN_NAME}" \
            -c siteAssetsPath="${GITHUB_WORKSPACE}/dist"
        working-directory: cdk
